using System;
/*
  - this is still required even in top-level call
    as you want to access the generated swaggerClient 
*/
using ConsoleUI;


/*
  - swaggerClient is auto-generated by adding a OpenAPI 
    connected service reference and specifying the source
    to swagger.json located in the project folder.
  - swagger.json is downloaded from the swagger UI in
    the WebAPIDemo
  - swaggerClient is located in the obj folder
*/

swaggerClient client = new("https://localhost:44345", new());

// you can use async/await in top-level call
var result = await client.WeatherForecastAsync();


foreach (var item in result)
{
    Console.WriteLine(item.Summary);
}